### ISSUE TITLE
"E85: There is no listed buffer" when starting vim with directory

### ISSUE THREAD

**Issue by dbeecham** [rbong/neovim-vifm#1]
To reproduce:

* `vim .`
* open file in Vifm

> Error detected while processing function <SNR>49_VifmExitCallback[14]..VifmClose:
> line 17:
> E85: There is no listed buffer

**Comment by xaizek** [comment]
Thanks for the report, @dbeecham.

@rbong, the error is caused by `:bprev` failing to operate when there is no previous buffer. I guess we can just add `silent!` in front of it, but maybe you know a better solution?
