### ISSUE TITLE
Automatic closing of vifm window after vifm exits when using :q command

### ISSUE THREAD

**Issue by sahilsehwag** [rbong/neovim-vifm#7]
When closing vifm with :q command. [Process Exited 0] is shown. It would be good if you can add :close  or :bdelete! in VifmExitCallback function whenever exiting.

**Comment by rbong** [comment]
I encountered this while merging with `vifm.vim`. This plugin is now deprecated. It should now be fixed there.

https://github.com/vifm/vifm.vim
